//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IgishevSchoolEntities6 : DbContext
    {
        private static IgishevSchoolEntities6 _context;
        public IgishevSchoolEntities6()
            : base("name=IgishevSchoolEntities6")
        {
        }

        public static IgishevSchoolEntities6 GetContext()
        {
            if (_context == null)
                _context = new IgishevSchoolEntities6();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductSale> ProductSales { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
